categories/urls.py
from django.urls import path

from .views import (
    categories_view, 
    products_category_view,
    
    create_category_view, 
    update_category_view,
    delete_category_view,
)

app_name = 'categories'

urlpatterns = [
    path('', categories_view, name='categories'),
    path('products_category/<int:pk>', products_category_view, name="products_category"),
    
    path('create_category/', create_category_view, name='create_category'),
    path('update_category/<int:pk>', update_category_view, name='update_category'),
    path('delete_category/<int:pk>', delete_category_view, name='delete_category'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import (
    home_view,
    about_view,
    register_view,
    login_view,
    logout_view
)

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', home_view, name='home'),
    path('about', about_view, name='about'),
    
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    
    path('categories/', include('categories.urls', namespace='categories')),
    path('products/', include('products.urls', namespace='products')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path

from .views import (
    products_view,
    create_product_view,
    detail_product_view,
    update_product_view,
    delete_product_view,
)

app_name = 'products'

urlpatterns = [
    path('', products_view, name='products'),
    path('create_product/', create_product_view, name='create_product'),
    path('detail_product/<int:pk>', detail_product_view, name='detail_product'),
    path('update_product/<int:pk>', update_product_view, name='update_product'),
    path('delete_product/<int:pk>', delete_product_view, name='delete_product'),
]

categories/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class CategoryModel(models.Model):
    name = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['name']
    
    def __str__(self):
        return self.name
    

categories/forms.py
from django import forms

from .models import CategoryModel

class CategoryForm(forms.ModelForm):
    class Meta:
        model = CategoryModel
        fields = ['name',]

categories/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import CategoryModel
from products.models import ProductModel
from .forms import CategoryForm

# Create your views here.

@login_required
def categories_view(request):
    categories = CategoryModel.objects.filter(user=request.user)
    
    category_totals = {} 

    for category in categories:
        products = ProductModel.objects.filter(user=request.user, category=category.pk)
        total = sum(product.price * product.stock for product in products)
        category_totals[category.name] = total

    return render(request, 'categories/categories.html', {
        'categories': categories,
        'category_totals': category_totals,
    })

@login_required
def products_category_view(request, pk):
    category = get_object_or_404(CategoryModel, pk=pk, user=request.user)
    products_category = ProductModel.objects.filter(user=request.user, category=pk)
    return render(request, 'categories/products_category.html', {
        'category' : category,
        'products' : products_category,
    })

@login_required
def create_category_view(request):
    form = CategoryForm(request.POST or None)
    
    if request.method == 'POST':
        if form.is_valid():
            new_category = form.save(commit=False)
            new_category.user = request.user
            new_category.save()
            messages.success(request, 'Category create successfully')
            return redirect('categories:categories')
        
        else:
            messages.warning(request, 'Error data incorrect')
    
    context = {
        'form' : form,
    }
    return render(request, 'categories/create_category.html', context)

@login_required
def update_category_view(request, pk):
    category = get_object_or_404(CategoryModel, pk=pk, user=request.user)
    form = CategoryForm(request.POST or None, instance=category)
    
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, 'Category updated successfully')
            return redirect('categories:categories')
        else:
            messages.warning(request, 'Error data incorrect')
    
    context = {
        'form' : form,
    }
    return render(request, 'categories/update_category.html', context)

@login_required
def delete_category_view(request, pk):
    category = get_object_or_404(CategoryModel, pk=pk, user=request.user)
    category.delete()
    messages.success(request, 'Categrory delete successfully')
    return redirect('categories:categories')

templates/categories/categories.html
<!-- categories.html -->
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock navbar %}

{% block content %}
    {% include 'components/messages.html' %}

    <div class="container">
        <h1>Categories</h1>

        <a href="{% url 'categories:create_category' %}"><button class="create">Create Category</button></a>

        {% if categories.exists %}
            <div class="grid">
                {% for category in categories %}
                    <div class="card">
                        <h2><a href="{% url 'categories:products_category' category.id %}">{{ category.name }}</a></h2>
                        
                        {% for name, total in category_totals.items %}
                            {% if category.name == name %}
                            <p>Total: {{ total|intcomma }}</p>
                            {% endif %}
                        {% endfor %}
                
                        <a href="{% url 'categories:update_category' category.id %}"><button class="update">Update</button></a>
                        <a href="{% url 'categories:delete_category' category.id %}"><button class="delete">Delete</button></a>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>You have not created categories yet</p>
            <img src="{% static 'patito.gif' %}" alt="">
        {% endif %}
    </div>
{% endblock content %}

templates/categories/create_category.html
{% extends 'base.html' %}

{% block navbar %}

{% include 'components/navbar.html' %}

{% endblock navbar %}

{% block content %}

<div class="form-container">
    <h4>Create Category</h4>

    {% include 'components/messages.html' %}

    <form action="" class="form-group" method="POST">
        {% csrf_token %}
        {{ form }}

        <button type="submit">create</button>
    </form>

</div>

{% endblock content %}

templates/categories/products_category.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block navbar %}

{% include 'components/navbar.html' %}

{% endblock navbar %}

{% block content %}

{% include "components/messages.html" %}


<div class="container">
    <h1>Products in  {{ category.name }}</h1>

    <a href="{% url 'products:create_product' %}"><button class="create">Create Product</button></a>

    {% if products.exists %}
        <div class="grid">
            {% for product in products %}
            <div class="card">
            <h2>
                <a href="{% url 'products:detail_product' product.id %}">{{ product.name }}</a>
            </h2>
            <p><strong>Total:</strong> {{ product.total_display|intcomma }}</p>
                <a href="{% url 'products:update_product' product.id %}"><button class="update">update</button></a>
                <a href="{% url 'products:delete_product' product.id %}"><button class="delete">delete</button></a>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <p>You have not created products in this category</p>
        <img src="{% static 'patito.gif' %}" alt="">
    {% endif %}
</div>

{% endblock content %}

templates/categories/update_category.html
{% extends 'base.html' %}

{% block navbar %}

{% include 'components/navbar.html' %}

{% endblock navbar %}

{% block content %}

<div class="form-container">
    <h4>Update Category</h4>

    {% include 'components/messages.html' %}

    <form action="" class="form-group" method="POST">
        {% csrf_token %}
        {{ form }}

        <button type="submit">update</button>
    </form>

</div>

{% endblock content %}