categories/urls.py
from django.urls import path

from .views import (
    categories_view, 
    products_category_view,
    
    create_category_view, 
    update_category_view,
    delete_category_view,
)

app_name = 'categories'

urlpatterns = [
    path('', categories_view, name='categories'),
    path('products_category/<int:pk>', products_category_view, name="products_category"),
    
    path('create_category/', create_category_view, name='create_category'),
    path('update_category/<int:pk>', update_category_view, name='update_category'),
    path('delete_category/<int:pk>', delete_category_view, name='delete_category'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import (
    home_view,
    about_view,
    register_view,
    login_view,
    logout_view
)

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', home_view, name='home'),
    path('about', about_view, name='about'),
    
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    
    path('categories/', include('categories.urls', namespace='categories')),
    path('products/', include('products.urls', namespace='products')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path

from .views import (
    products_view,
    create_product_view,
    detail_product_view,
    update_product_view,
    delete_product_view,
)

app_name = 'products'

urlpatterns = [
    path('', products_view, name='products'),
    path('create_product/', create_product_view, name='create_product'),
    path('detail_product/<int:pk>', detail_product_view, name='detail_product'),
    path('update_product/<int:pk>', update_product_view, name='update_product'),
    path('delete_product/<int:pk>', delete_product_view, name='delete_product'),
]

templates/components/messages.html
{% load static %}

{% if messages %}
{% for message in messages %}
<div class="alert">
    <h2 class="alert-title">{{ message.tags }}</h2>
    <p class="alert-message">{{ message }}</p>
    <button class="alert-button">Dismiss</button>
</div>
{% endfor %}
{% endif %}

templates/components/navbar.html
{% load static %}
<header class="header">
    <div class="logo">
        <img src="{% static 'logo.png' %}" alt="">
    </div>
    <nav>
        <ul class="nav-links">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            {% if request.user.is_authenticated %}
                        <li><a href="{% url 'products:products' %}">Products</a></li>
                        <li><a href="{% url 'categories:categories' %}">Categories</a></li>
                
                    </ul>
                </nav>
                <a href="{% url 'logout' %}" class="btn"><button>Logout</button></a>
            {% else %}
                </nav>
                <a href="{% url 'register' %}" class="btn"><button>Register</button></a>
                <a href="{% url 'login' %}" class="btn"><button>Login</button></a>
            {% endif %}  
        
        <a onclick="openNav()"  href="#"  class="menu"><button>Menu</button></a>
    
        <div class="overlay" id="mobile-menu">
            <a onclick="closeNav()" href="" class="close">&times;</a>
            <div class="overlay-content">
                <a href="{% url 'home' %}">Home</a> 
                <a href="{% url 'about' %}">About</a>   
                {% if request.user.is_authenticated %}
                    <a href="{% url 'products:products' %}">Products</a>    
                    <a href="{% url 'categories:categories' %}">Categories</a>  
                    <a href="{% url 'logout' %}" class="btn"><button>Logout</button></a>
                    {% else %}
                        <a href="{% url 'register' %}" class="btn"><button>Register</button></a>
                        <a href="{% url 'login' %}" class="btn"><button>Login</button></a>
                    {% endif %}
            </div>
        </div>
</header>